project:
  type: book
  output-dir: docs

book:
  title: "Argo User's manual"
  subtitle: "Version 3.42.0"
  author: "Argo data management team"
  date: 05/26/2025
  doi: 10.13155/29825
  chapters:
    - index.qmd
    - chapter1.qmd
    - chapter2.qmd
    - chapter3.qmd
    - chapter4.qmd
    - chapter5.qmd
    - chapter6.qmd
    - chapter7.qmd

format:
  html:
    theme:
      light: yeti
      dark: darkly
    css: assets/css/styles.css
    toc: true
    include-after-body:
      - assets/js/script.js.html


resources:
  - "assets/json/"
  - "assets/images/"
  - "assets/js/"

