project:
  type: book

book:
  title: "Argo User's manual"
  author: "Argo data management team"
  date: 03/28/2025
  doi: 10.13155/29825
  chapters:
    - index.qmd
    - chapter1.qmd
    - chapter2.qmd

format:
  html:
    theme:
      light: yeti
      dark: darkly
    css: assets/css/styles.css
    toc: true
    include-after-body:
      - assets/js/script.js.html
  pdf:
    documentclass: scrreprt


resources:
  - "assets/json/"
  - "assets/images/"
  - "assets/js/"

