project:
  type: book

book:
  title: "Argo User's manual"
  author: "Thierry Carval"
  chapters:
    - index.qmd
    - chapter1.qmd
    - chapter2.qmd

format:
  html:
    theme:
      light: yeti
      dark: darkly
    css: assets/css/styles.css
    toc: true
    include-after-body:
      - assets/js/script.js.html



resources:
  - "assets/json/"
  - "assets/images/"
  - "assets/js/"

